import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', backgroundColor: '#ffffff' },
  header: { borderBottom: '1pt solid #1e3456', paddingBottom: 10, marginBottom: 20 },
  appTitle: { fontSize: 10, color: '#64748b', textTransform: 'uppercase', marginBottom: 4 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#0B1F3A', marginBottom: 10 },
  subtitle: { fontSize: 12, color: '#64748b', marginBottom: 20 },
  
  section: { marginBottom: 30 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#0B1F3A', borderBottom: '1pt solid #e2e8f0', paddingBottom: 5, marginBottom: 10 },
  
  row: { flexDirection: 'row', marginBottom: 5 },
  label: { width: '30%', fontSize: 10, color: '#64748b', fontWeight: 'bold' },
  value: { width: '70%', fontSize: 10, color: '#0f172a' },
  
  table: { width: '100%', marginBottom: 10 },
  tableHeader: { flexDirection: 'row', backgroundColor: '#f8fafc', borderBottom: '1pt solid #cbd5e1', padding: 5 },
  tableRow: { flexDirection: 'row', borderBottom: '1pt solid #e2e8f0', padding: 5 },
  tableCell: { fontSize: 9, color: '#334155' },
  tableCellBold: { fontSize: 9, fontWeight: 'bold', color: '#0f172a' },
  
  gradeBox: { marginTop: 10, padding: 20, backgroundColor: '#f8fafc', borderRadius: 8, flexDirection: 'row', alignItems: 'center' },
  gradeLetter: { fontSize: 48, fontWeight: 'bold', width: '30%', textAlign: 'center' },
  gradeDetails: { width: '70%', paddingLeft: 20, borderLeft: '1pt solid #cbd5e1' },
  gradeLabel: { fontSize: 10, color: '#64748b' },
  gradeVal: { fontSize: 14, fontWeight: 'bold', color: '#0f172a', marginBottom: 5 },

  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTop: '1pt solid #e2e8f0', paddingTop: 10, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#94a3b8' }
});

const getGradeColor = (grade: string) => {
  switch (grade) {
    case 'A': return '#10b981';
    case 'B': return '#14b8a6';
    case 'C': return '#f59e0b';
    case 'D': return '#f97316';
    case 'E': return '#f43f5e';
    default: return '#64748b';
  }
};

const Footer = ({ imo }: { imo: string }) => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>IMO: {imo}</Text>
    <Text style={styles.footerText}>Generated by Vessel CII Dashboard</Text>
    <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
  </View>
);

export const PdfReportTemplate = ({ data }: { data: any }) => {
  const { vessel, year, rating, fuelData, docs, topVoyages, mode } = data;
  const generationDate = new Date().toLocaleDateString();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Cover / Header */}
        <View style={styles.header}>
          <Text style={styles.appTitle}>{mode === 'COMMERCIAL' ? 'Vessel CII Dashboard' : 'Fleet Readiness Dashboard'}</Text>
          <Text style={styles.title}>{mode === 'COMMERCIAL' ? 'Annual CII Compliance Report' : 'Annual Fleet Readiness Report'}</Text>
          <Text style={styles.subtitle}>Reporting Year: {year} | Generated: {generationDate}</Text>
          
          <View style={styles.row}>
            <Text style={styles.label}>Vessel Name:</Text>
            <Text style={styles.value}>{vessel.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{mode === 'COMMERCIAL' ? 'IMO Number:' : 'Hull / Pennant:'}</Text>
            <Text style={styles.value}>{vessel.imoNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Vessel Type:</Text>
            <Text style={styles.value}>{vessel.type.replace('_', ' ')}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Flag State:</Text>
            <Text style={styles.value}>{vessel.flagState}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Gross Tonnage:</Text>
            <Text style={styles.value}>{vessel.grossTonnage.toLocaleString()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Deadweight:</Text>
            <Text style={styles.value}>{vessel.deadweight.toLocaleString()} MT</Text>
          </View>
        </View>

        {/* Section 2: CII Performance */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{mode === 'COMMERCIAL' ? 'Section 1: CII Performance' : 'Section 1: Fleet Energy Performance'}</Text>
          {rating ? (
            <View style={styles.gradeBox}>
              <Text style={{ ...styles.gradeLetter, color: getGradeColor(rating.rating) }}>
                {rating.rating}
              </Text>
              <View style={styles.gradeDetails}>
                <Text style={styles.gradeLabel}>{mode === 'COMMERCIAL' ? 'Attained CII (AER)' : 'Attained Energy Index'}</Text>
                <Text style={styles.gradeVal}>{rating.attainedCii.toFixed(2)}</Text>
                <Text style={styles.gradeLabel}>{mode === 'COMMERCIAL' ? 'Required CII' : 'Fleet Energy Target'}</Text>
                <Text style={styles.gradeVal}>{rating.requiredCii.toFixed(2)}</Text>
              </View>
            </View>
          ) : (
            <Text style={styles.value}>No CII Rating available for {year}.</Text>
          )}
        </View>

        {/* Section 1: Fuel Consumption */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Section 2: Fuel Consumption Summary</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={{ ...styles.tableCellBold, width: '30%' }}>Fuel Type</Text>
              <Text style={{ ...styles.tableCellBold, width: '25%' }}>Quantity (MT)</Text>
              <Text style={{ ...styles.tableCellBold, width: '25%' }}>CO₂ Equiv (t)</Text>
              <Text style={{ ...styles.tableCellBold, width: '20%' }}>% of Total</Text>
            </View>
            {fuelData.map((f: any, i: number) => (
              <View key={i} style={styles.tableRow}>
                <Text style={{ ...styles.tableCell, width: '30%' }}>{f.fuelType}</Text>
                <Text style={{ ...styles.tableCell, width: '25%' }}>{f.quantity.toFixed(1)}</Text>
                <Text style={{ ...styles.tableCell, width: '25%' }}>{f.co2.toFixed(1)}</Text>
                <Text style={{ ...styles.tableCell, width: '20%' }}>{f.percentage.toFixed(1)}%</Text>
              </View>
            ))}
          </View>
        </View>

        <Footer imo={vessel.imoNumber} />
      </Page>

      <Page size="A4" style={styles.page}>
        {/* Section 3: Compliance Documents */}
        {mode === 'COMMERCIAL' && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Section 3: Compliance Documents</Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                <Text style={{ ...styles.tableCellBold, width: '30%' }}>Document</Text>
                <Text style={{ ...styles.tableCellBold, width: '20%' }}>Status</Text>
                <Text style={{ ...styles.tableCellBold, width: '25%' }}>Expiry Date</Text>
                <Text style={{ ...styles.tableCellBold, width: '25%' }}>Days Remaining</Text>
              </View>
              {docs.map((doc: any, i: number) => (
                <View key={i} style={styles.tableRow}>
                  <Text style={{ ...styles.tableCell, width: '30%' }}>{doc.documentType}</Text>
                  <Text style={{ ...styles.tableCell, width: '20%' }}>{doc.status}</Text>
                  <Text style={{ ...styles.tableCell, width: '25%' }}>{doc.expiryDate ? new Date(doc.expiryDate).toLocaleDateString() : 'N/A'}</Text>
                  <Text style={{ ...styles.tableCell, width: '25%' }}>{doc.daysRemaining !== null ? doc.daysRemaining : 'N/A'}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* Section 4: Voyage Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{mode === 'COMMERCIAL' ? 'Section 4: Top 10 Voyages by Distance' : 'Section 2: Top 10 Sorties by Distance'}</Text>
          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={{ ...styles.tableCellBold, width: '30%' }}>Route</Text>
              <Text style={{ ...styles.tableCellBold, width: '20%' }}>Departure</Text>
              <Text style={{ ...styles.tableCellBold, width: '20%' }}>Distance (nm)</Text>
              <Text style={{ ...styles.tableCellBold, width: '15%' }}>Fuel (MT)</Text>
              <Text style={{ ...styles.tableCellBold, width: '15%' }}>Cargo (MT)</Text>
            </View>
            {topVoyages.map((v: any, i: number) => (
              <View key={i} style={styles.tableRow}>
                <Text style={{ ...styles.tableCell, width: '30%' }}>{v.departurePort} to {v.arrivalPort}</Text>
                <Text style={{ ...styles.tableCell, width: '20%' }}>{new Date(v.departureTime).toLocaleDateString()}</Text>
                <Text style={{ ...styles.tableCell, width: '20%' }}>{v.distanceSailed.toFixed(0)}</Text>
                <Text style={{ ...styles.tableCell, width: '15%' }}>{v.totalFuel.toFixed(1)}</Text>
                <Text style={{ ...styles.tableCell, width: '15%' }}>{v.cargoCarried || 'N/A'}</Text>
              </View>
            ))}
          </View>
        </View>

        <Footer imo={vessel.imoNumber} />
      </Page>
    </Document>
  );
};
